image: continuumio/miniconda3:latest
# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

before_script:
  - python -V               # Print out python version for debugging
  - apt update && apt install -y gfortran mpi-default-dev
  - pip install cython
  - conda install -y -c conda-forge galario
  - pip install .

test:
  script:
  - pip install pytest-cov
  - cd diskchef
  - pytest --doctest-modules --cov diskchef

pages:
  stage: deploy
  script:
    - shopt -s extglob
    - pip install pdoc3 pytest-cov
    - pdoc --html diskchef --overwrite
    - mkdir -p cache/$CI_COMMIT_BRANCH
    - rm -rf cache/$CI_COMMIT_BRANCH/*
    - cp -r html/diskchef/* cache/$CI_COMMIT_BRANCH/
    - cp -r cache public
  artifacts:
    paths:
      - public
  only:
    - master

#     when: always
