image: continuumio/miniconda3:latest
# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

stages:
  - install
  - test
  - deploy_docs

pipinstall:
  stage: install
  script:
    - python -V               # Print out python version for debugging
    - apt update && apt install -y gfortran mpi-default-dev
    - pip install cython
    - conda install -y -c conda-forge galario
    - pip install .

pytest:
  stage: test
  script:
  - pip install pytest-cov
  - cd diskchef
  - pytest --doctest-modules --cov diskchef

test_example:
  stage: test
  needs: [pytest]
  script:
  - cd examples
  - python example_user_physics.py
  - python example_wb_chemistry.py
  - cd lines && python example_rt_lines.py && cd ..
  - cd example_andes && python example_andes.py && cd ..


pages:
  stage: deploy_docs
  script:
    - mkdir -p public
    - pip install pdoc3 pytest-cov
    - pdoc --html diskchef --overwrite
    - cp -r html/diskchef/* public/
  artifacts:
    paths:
      - public
  only:
    - master