image: python:3.8

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

before_script:
  - python -V               # Print out python version for debugging
  - pip install .

test:
  script:
  - pip install pytest-cov
  - cd diskchef
  - pytest --doctest-modules --cov diskchef

pages:
  script:
  - pip install pdoc3 pytest-cov
  - pdoc --html diskchef --overwrite
  - mv html/diskchef/ public/
  artifacts:
    paths:
    - public
  only:
  - master

