image: continuumio/miniconda3:latest
# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

before_script:
  - python -V               # Print out python version for debugging
  - apt update && apt install -y gfortran
  - conda install -y -c conda-forge mpi4py openmpi galario cython
  - pip install .

test:
  script:
  - pip install pytest-cov
  - cd diskchef
  - pytest --doctest-modules --cov diskchef

pages:
  stage: deploy
  script:
    - mkdir -p public
    - pip install pdoc3 pytest-cov
    - pdoc --html diskchef --overwrite
    - cp -r html/diskchef/* public/
  artifacts:
    paths:
      - public
  only:
    - master