image: continuumio/miniconda3:latest
# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

before_script:
  - python -V               # Print out python version for debugging
  - apt update && apt install -y gfortran
  - pip install cython
  - conda install -y -c conda-forge galario
  - pip install .

test:
  script:
  - pip install pytest-cov
  - cd diskchef
  - pytest --doctest-modules --cov diskchef

pages:
  stage: deploy
  script:
    - shopt -s extglob
    - pip install pdoc3 pytest-cov
    - pdoc --html diskchef --overwrite
    - mkdir -p cache/$CI_COMMIT_BRANCH
    - rm -rf cache/$CI_COMMIT_BRANCH/*
    - cp -r html/diskchef/* cache/$CI_COMMIT_BRANCH/
    - cp -r cache public
  artifacts:
    paths:
      - public
  only:
    - master

# pylint:
#   stage: test
#   before_script:
#     - mkdir -p public/badges public/lint
#     - echo undefined > public/badges/$CI_JOB_NAME.score
#     - pip install pylint_gitlab
#   script:
#     - pylint --exit-zero --output-format=text $(find -type f -name "*.py" ! -path "**/.venv/**") | tee /tmp/pylint.txt
#     - sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' /tmp/pylint.txt > public/badges/$CI_JOB_NAME.score
#     - pylint --exit-zero --output-format=pylint_gitlab.GitlabCodeClimateReporter diskchef > codeclimate.json
#     - pylint --exit-zero --output-format=pylint_gitlab.GitlabPagesHtmlReporter diskchef > public/lint/index.html
#   after_script:
#     - anybadge --overwrite --label $CI_JOB_NAME --value=$(cat public/badges/$CI_JOB_NAME.score) --file=public/badges/$CI_JOB_NAME.svg 4=red 6=orange 8=yellow 10=green
#     - |
#       echo "Your score is: $(cat public/badges/$CI_JOB_NAME.score)"
#   artifacts:
#     paths:
#       - public
#     reports:
#       codequality: codeclimate.json
#     when: always
