stages:
  - bootstrap
  - build-diskchef
  - test
  - deploy_docs

variables:
  DISKCHEF_IMAGE: "${CI_REGISTRY_IMAGE}/diskchef"

bootstrap:
  image: docker
  stage: bootstrap
  only:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^DISKCHEF-bootstrap*/
  services:
    - docker:dind
  before_script:
    - export IMAGE="${CI_REGISTRY_IMAGE}/bootstrap:latest"
    - echo $IMAGE
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - cd bootstrap
    - docker build -t $IMAGE .
    - docker push $IMAGE

build-diskchef:
  image: docker
  stage: build-diskchef
 
  services:
    - docker:dind
  before_script:
    - export IMAGE_LATEST="${DISKCHEF_IMAGE}:latest"
    - echo $IMAGE_LATEST
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -t $IMAGE_LATEST .
    - docker push $IMAGE_LATEST

image: ${DISKCHEF_IMAGE}


pytest:
  stage: test
  script:
  - pip install pytest-cov
  - cd diskchef
  - pytest --doctest-modules --cov diskchef

test_example:
  stage: test
  needs: [pytest]
  script:
  - cd examples
  - python example_user_physics.py
  - python example_wb_chemistry.py
  - cd lines && python example_rt_lines.py && cd ..
  - cd example_andes && python example_andes.py && cd ..


pages:
  stage: deploy_docs
  script:
    - mkdir -p public
    - pip install pdoc3 pytest-cov
    - pdoc --html diskchef --overwrite
    - cp -r html/diskchef/* public/
  artifacts:
    paths:
      - public
  only:
    - master