image: continuumio/anaconda3:2020.07

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

before_script:
  - python -V               # Print out python version for debugging
  - pip install -r requirements.txt .

test:
  script:
  - pip install pytest-cov
  - cd diskchef/tests
  - pytest --cov diskchef

#run:
#  script:
#  - python setup.py bdist_wheel
#  # an alternative approach is to install and run:
#  - pip install dist/*
#  # run the command here
#  artifacts:
#    paths:
#    - dist/*.whl

pages:
  script:
  - pip install pdoc3
  - pdoc --html diskchef --overwrite
  - mv html/diskchef/ public/
  artifacts:
    paths:
    - public
  only:
  - master

